module.exports.code = [
    'ICS',
    'SWE',
    'CISE',
    'CHE',
    'BUS',
    'MATH',
    'PHYS',
    'BIO',
    'CHEM',
    'ENG',
    'ME',
    'EE',
    'CIE',
    'MSE',
    'PETE'
]

module.exports.deptName = [
    'Computer Science',
    'Software Engineering',
    'Computer Information Systems',
    'Chemical Engineering',
    'Business Administration',
    'Mathematics',
    'Physics',
    'Biology',
    'Chemistry',
    'English',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Materials Science and Engineering',
    'Petroleum Engineering'
]
module.exports.first = [
    'Hamoud',
    'Hamoud',
    'Mujahed',
    'Khaled',
    'Abdullah',
    'Monther',
    'Mohammad',
    'Ali',
    'Naif',
    'Malcolm',
    'Ahmad',
    'Abdulrahman',
    'Abdulaziz',
    'Aimen',
    'Abdulmohsen',
]

module.exports.last = [
    'Aljomaan',
    'Aljomaan',
    'Alghamdi',
    'Alotaibi',
    'Alzahrani',
    'Alforaidan',
    'Alkuhaili',
    'Alghamdi',
    'Alotaibi',
    'Bancroft',
    'Alzahrani',
    'Alforaidan',
    'Alkuhaili',
    'Alghamdi',
    'Alotaibi',
]