module.exports.fname = [
    'Ali',
    'Mohammad',
    'Ahmad',
    'Abdullah',
    'Abdulrahman',
    'Abdulaziz',
    'Abdulmohsen',
    'Jaafar',
    'Reda',
    'Hasaan',
    'Hussain',
    'Hussam',
    'Saud',
    'Salem',
]
module.exports.lname = [
    'Almalki',
    'Alghamdi',
    'Alotaibi',
    'Alfuraidan',
    'Almahdood',
    'Almuallim',
    'Almuhanna',
    'Altalaq',
    'Alzahrani',
    'Alabdulaal'
]

module.exports.ids = [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36'

]
module.exports.emails = [
    'Ali@gmail.com',
    'Mohammad@gmail.com',
    'Ahmad@gmail.com',
    'Abdullah@gmail.com',
    'Abdulrahman@gmail.com',
    'Abdulaziz@gmail.com',
    'Abdulmohsen@gmail.com',
    'Jaafar@gmail.com',
    'Reda@gmail.com',
    'Hassan@gmail.com',
    'Hussain@gmail.com',
    'Hussan@gmai.com',
    'Saud@gmail.com',
    'Salem@gmail.com'
]

module.exports.bdates = [
    new Date(1999, 4, 20),
    new Date(1999, 4, 21),
    new Date(1999, 4, 22),
    new Date(1999, 4, 23),
    new Date(1999, 4, 24),
    new Date(1999, 4, 25),
    new Date(1999, 4, 26),
    new Date(1999, 4, 27),
    new Date(1999, 4, 28),
    new Date(1999, 4, 29),
    new Date(1999, 4, 30),
    new Date(1999, 4, 31),
    new Date(1999, 5, 1),
    new Date(1999, 5, 2),
    new Date(1999, 5, 3),
    new Date(1999, 5, 4),
    new Date(1999, 5, 5),
    new Date(1999, 5, 6)
]
module.exports.deptCode = [
    'ICS',
    'SWE',
    'CISE',
    'CHE',
    'BUS',
    'MATH',
    'PHYS',
    'BIO',
    'CHEM',
    'ENG',
    'ME',
    'EE',
    'CIE',
    'MSE',
    'PETE'
]