// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtydeOBhnvL6v2WfcoAx4c0wvnq8wTYr4',
    appId: '1:247856903398:web:9ba7d102ba45bccd36f727',
    messagingSenderId: '247856903398',
    projectId: 'ics-321-project-49853',
    authDomain: 'ics-321-project-49853.firebaseapp.com',
    storageBucket: 'ics-321-project-49853.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80-j8MKEGeH6xmjWlXJckDjwvvFBv_F0',
    appId: '1:247856903398:android:bdcfadcc5490996236f727',
    messagingSenderId: '247856903398',
    projectId: 'ics-321-project-49853',
    storageBucket: 'ics-321-project-49853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMvbuZ_e_sTl_R2k3-vLmHCGF6YfxBpCI',
    appId: '1:247856903398:ios:5f296666416d7b9536f727',
    messagingSenderId: '247856903398',
    projectId: 'ics-321-project-49853',
    storageBucket: 'ics-321-project-49853.appspot.com',
    iosClientId: '247856903398-9mtdsf1s4er4ihhpbk34trfbud61vq6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.kfupmSoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMvbuZ_e_sTl_R2k3-vLmHCGF6YfxBpCI',
    appId: '1:247856903398:ios:5f296666416d7b9536f727',
    messagingSenderId: '247856903398',
    projectId: 'ics-321-project-49853',
    storageBucket: 'ics-321-project-49853.appspot.com',
    iosClientId: '247856903398-9mtdsf1s4er4ihhpbk34trfbud61vq6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.kfupmSoc',
  );
}
